# Generated by Django 4.0 on 2022-03-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0014_likearticle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likearticle',
            unique_together={('user', 'article')},
        ),
    ]
